name: sixvalley_delivery_boy
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  get: ^4.1.4
  http: ^0.13.3
  shared_preferences: ^2.0.5
  dio: ^4.0.0-prev3
  google_maps_flutter: ^2.0.1
  geocoding: ^2.0.0
  geolocator: ^8.2.0
  url_launcher: ^6.0.2
  url_strategy: ^0.2.0
  flutter_local_notifications: ^9.3.2
  path_provider: ^2.0.2
  vibration: ^1.7.4-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  flutter_widget_from_html_core: ^0.8.5+1
  image_picker: ^0.8.0+4
  intl: ^0.17.0
  connectivity: ^3.0.6
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.3
  country_code_picker: ^2.0.2
  expandable: ^5.0.1
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^1.0.0
  timeago: ^3.3.0
  dotted_border: ^2.0.0+2
  expandable_bottom_sheet: ^1.1.1+1
  syncfusion_flutter_datepicker: ^20.3.47
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^4.1.1
  flutter_html: ^3.0.0-alpha.3
  pin_code_fields: ^7.0.0
  readmore: ^2.2.0
  cached_network_image: ^3.2.2


dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700